name: Bug report
description: Report something that is broken or incorrect
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        **Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)
        detailing how to provide the necessary information for us to reproduce your bug. In brief:
          * Please provide exact steps how to reproduce the bug in a clean Python environment.
          * In case it's not clear what's causing this bug, please provide the data or the data generation procedure.
          * Sometimes it is not possible to share the data, but usually it is possible to replicate problems on publicly
            available datasets or to share a subset of your data.

  - type: textarea
    id: report
    attributes:
      label: Report
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: versions
    attributes:
      label: Version information
      description: |
        Please paste below the output of

        ```python
        import session_info
        session_info.show(html=False, dependencies=True)
        ```
      placeholder: |
        -----
        dbcan               0.1.dev357+g4e1041c.d20240223
        session_info        1.0.0
        -----
        google              NA
        sphinxcontrib       NA
        -----
        Python 3.10.13 (main, Nov 15 2023, 11:07:58) [Clang 14.0.0 (clang-1400.0.29.202)]
        macOS-12.7.3-x86_64-i386-64bit
        -----
        Session information updated at 2024-02-22 20:12
