name: Run dbcan Tests
# spell-checker:ignore dbcan

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

    schedule:
        - cron: '0 5 1,15 * *'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true




jobs:
    test:
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                shell: bash -l {0} # -e to fail on error

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-13]
                python: ["3.10", "3.11", "3.12", "3.13"]

        name: ${{ matrix.name }} Python ${{ matrix.python }}

        env:
            OS: ${{ matrix.os }}
            PYTHON: ${{ matrix.python }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up conda
              uses: conda-incubator/setup-miniconda@v3
              with:
                mamba-version: "*"
                auto-update-conda: true
                auto-activate-base: false
                python-version: ${{ matrix.python }}
                channels: conda-forge, bioconda, defaults
                environment-file: envs/test_environment.yml
                activate-environment: test_dbcan

            - name: Install dependencies
              run: |
                    pip install pytest
                    pip install -e ".[dev,test]"


            - name: run dbCAN test
              run: |
                    pytest tests/test_dbcan.py -v
